#include <iostream>
#include <string>

using namespace std;

int main() {
    string a;

    cout << "AD ASTRA ABYSSOSQUE. WHAT DO YOU WANT TO KNOW, TRAVELER?: ";
    cin >> a;

    if (a == "ADVENTURE RANK") {
        cout << "A LEVEL SYSTEM THAT IS TIED TO YOUR ACCOUNT.";
    }else if (a == "WORLD LEVEL") {
        cout << "A SYSTEM THAT INCREASES THE DIFFICULTY OF THE WORLD AS YOU PROGRESS.";
    }else if (a == "DAILY COMMISIONS") {
        cout << "GIVEN EVERY DAY, OFFERING MORA, EXPERIENCE, AND PRIMOGEMS AS REWARDS.";
    }else if (a == "PRIMOGEMS") {
        cout << "A SEMI-PREMIUM CURRENCY.";
    }else if (a == "GENESIS CRYSTALS") {
        cout << "THE MAIN PREMIUM CURRENCY.";
    }else if (a == "MORA") {
        cout << "THE PRIMARY CURRENCY, USED TO UPGRADE CHARACTERS, WEAPONS, AND ARTIFACTS.";
    }else if (a == "FATES") {
        cout << "SPECIAL ITEMS USED TO MAKE WISHES AND OBTAIN NEW CHARACTERS AND WEAPONS.";
	}else if (a == "STATUES OF THE SEVEN") {
        cout << "IMPORTANT CHECKPOINTS THAT WHEN UNLOCKED, REVEALS THE SURROUNDING AREA.";
    }else if (a == "OCULUS") {
        cout << "USED TO LEVEL UP STATUES OF THE SEVEN.";
    }else if (a == "TELEPORT WAYPOINTS") {
        cout << "TELEPORT TO THEM ANYTIME FROM YOUR MAP MAKING TRAVELLING LONG DISTANCES.";
    }else if (a == "ASCENSION") {
        cout << "LEVELING UP YOUR CHARACTER OR WEAPONS BEYOND THEIR NORMAL MAXIMUM LIMITS.";
    }else if (a == "CONSTELLATIONS") {
        cout << "SPECIAL ABILITIES OR BUFFS THAT ARE UNLOCKED WHEN YOU OBTAIN DUPLICATE COPIES OF A SPECIFIC CHARACTER.";
    }else if (a == "ARTIFACTS") {
        cout << "ARTIFACTS ARE ITEMS YOU GIVE CHARACTERS TO RAISE THEIR STATS.";
    }else if (a == "ALCHEMY") {
        cout << "A SYSTEM USED TO TRANSFORM MATERIALS INTO NEW ITEMS OR ELEMENTS.";
    }else if (a == "WEAPON FORGING") {
        cout << "A CRAFTING SYSTEM THAT ALLOWS TO FORGE NEW WEAPONS USING MATERIALS COLLECTED THROUGHOUT THE WORLD.";
    }else if (a == "BILLETS") {
        cout << "SPECIAL TYPE OF MATERIAL USED TO CRAFT WEAPONS.";
    }else if (a == "RESIN") {
        cout << "THE CURRENCY YOU USE IN EXCHANGE FOR CLAIMING REWARDS.";
    }else if (a == "BOSS MATERIALS") {
        cout << "ITEMS DROPPED BY WORLD BOSSES OR WEEKLY BOSSES USED FOR CHARACTER ASCENSION, TALENT LEVELING, AND CRAFTING.";
    }else if (a == "MONDSTADT") {
        cout << "A REGION FULL OF FREEDOM, WINDMILLS, AND LUSH GREEN FIELDS. THE PEOPLE HERE LOVE MUSIC AND FREEDOM.";
    }else if (a == "LIYUE") {
        cout << "A LAND FULL OF MOUNTAINS, RIVERS, AND ANCIENT TRADITIONS. THE PEOPLE VALUE COMMERCE, HARD WORK, AND STABILITY.";
    }else if (a == "INAZUMA") {
        cout << "A REGION FILLED WITH STORMS AND ELECTRICAL ENERGY. THE PEOPLE HERE VALUE ORDER AND CONTROL, BUT THE REGION IS ALSO KNOWN FOR ITS BEAUTIFUL ISLANDS.";
    }else if (a == "SNEZHNYA") {
        cout << "A FROSTY LAND FILLED WITH SNOW AND ICE. KNOWN FOR ITS COLD ENVIRONMENT AND SECRETS.";
    }else if (a == "SUMERU") {
        cout << "A MYSTERIOUS REGION FULL OF LUSH FORESTS, RICH PLANTLIFE, AND KNOWLEDGE. KNOWN FOR ITS CONNECTION TO WISDOM AND THE WORLD OF NATURE.";
    }else if (a == "FONTAINE") {
        cout << "A REGION FILLED WITH WATERWAYS, WATERFALLS, AND A BUSTLING WATER-BASED INDUSTRY. FONTANES IS A CITY OF LAW AND JUSTICE.";
    }else if (a == "NATLAN") {
        cout << "A REGION FULL OF FIERY LANDSCAPES, VOLCANOES, HOT CLIMATES, AND FIRE-BASED ELEMENTS. IT IS EXPECTED TO BE A REGION OF INTENSE PASSION AND ENERGY.";
    }else if (a == "KHAENRI'AH") {
        cout << "A FALLEN NATION MENTIONED IN THE GAME'S LORE, ASSOCIATED WITH THE ABYSS AND A MYSTERIOUS PAST.";
    }else if (a == "ABYSS") {
        cout << "A MYSTERIOUS, DARK, AND DANGEROUS DIMENSION THAT IS CENTRAL TO THE LORE.";
    }else if (a == "TEYVAT") {
        cout << "THE WORLD IN WHERE EVERYTHING TAKES PLACE, MADE UP OF SEVEN NATIONS EACH GOVERNED BY AN ARCHON AND ASSOCIATED WITH A UNIQUE ELEMENT.";
    }else if (a == "FATUI") {
        cout << "POWERFUL, INFLUENTIAL, AND OFTEN ANTAGONISTIC ORGANIZATION THAT OPERATES IN THE WORLD OF TEYVAT.";
    }else if (a == "ARCHON") {
        cout << "A POWERFUL, GOD-LIKE BEING WHO GOVERNS ONE OF THE SEVEN REGIONS OF TEYVAT.";
    }

    return 0;    
}
